export PROJECT = hostservice
IMPORT_PATH := github.com/kashifkhan0771/${PROJECT}

# all non-windows environments
ROOT := $(shell pwd)

DEV_IMAGE := ${PROJECT}_dev

DOCKRUN := docker run --rm \
	-v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
	${DEV_IMAGE}

DOCKTEST := docker run --rm \
    -v ${ROOT}:/${PROJECT}/src/${IMPORT_PATH} \
    --link host-service-mongo-db:host-service-mongo-db \
    --link host-service-mysql-db:host-service-mysql-db \
    ${DEV_IMAGE}
